query:
  fusion_subgraph: https://api.thegraph.com/subgraphs/name/ruvlol/retro-fusion
  day_data_fusion_query: {"operationName": "fusionDayDatas", "variables": {"startTime": 1690329600, "skip": 0}, "query": "query fusionDayDatas($startTime: Int!, $skip: Int!) {\n  fusionDayDatas(skip: $skip, where: {date_gt: $startTime}, orderBy: date, orderDirection: asc) {\n    id\n    date\n    volumeUSD\n    feesUSD\n    tvlUSD\n    __typename\n  }\n}\n"}
  pair_data_fusion_query: {"operationName":"pairDayDatasV3","variables":{"pairAddress":"0","skip":0,"startTime":1690329600},"query":"query pairDayDatasV3($pairAddress: Bytes!, $skip: Int!, $startTime: Int!) {\n  poolDayDatas(skip: $skip, orderBy: date, orderDirection: asc, where: {pool: $pairAddress, date_gt: $startTime}) {\n    id\n    date\n    tvlUSD\n    volumeUSD\n    volumeToken0\n    volumeToken1\n    token0Price\n    token1Price\n    feesUSD\n    __typename\n  }\n}"}
  
web3:
  provider_url: https://rpc.ankr.com/polygon
  
gsheets:
  daily_data_fusion_sheet_key: 1ksiupEzlwVBMmrE9OkBnoFeBkLT0_iOpR3p6OY4MPZI
  pair_data_fusion_sheet_key: 1j0242nHZD9Qz01mwYOLUfc9uLL17_2IKq5tx5dxw_Dg
  emissions_data_sheet_key: 
  revenue_data_sheet_key: 
  fee_data_sheet_key: 
  
api:
  price_api: https://retro-backend.stabl.finance/api/v1/assets
  fusion_api: https://retro-backend.stabl.finance/api/v1/fusions
  
files:
  epoch_data: https://raw.githubusercontent.com/ALMIGHTYABE/Retro-Data/main/data/epoch.csv
  epoch_daily_data: https://raw.githubusercontent.com/ALMIGHTYABE/Retro-Data/main/data/epoch_daily.csv
  id_data: https://raw.githubusercontent.com/ALMIGHTYABE/Retro-Data/main/data/ids_data.csv
  daily_data_fusion: https://docs.google.com/spreadsheets/d/1ksiupEzlwVBMmrE9OkBnoFeBkLT0_iOpR3p6OY4MPZI/export?format=csv
  pair_data_fusion: https://docs.google.com/spreadsheets/d/1j0242nHZD9Qz01mwYOLUfc9uLL17_2IKq5tx5dxw_Dg/export?format=csv
  emissions_data: 
  